spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: file:./app/
cds:
  odata-v4:
    endpoint:
      path: /
  remote.services:
    CATALOG_SERVICE:
      type: "odata-v4"
      model: CATALOG_SERVICE
      destination:
        name: "bookshopdest"
        properties:
          url: "https://sdmgoogleworkspacedev-developcap-demoappjava-srv.cfapps.eu12.hana.ondemand.com"
          authentication: TokenForwarding
  data-source.auto-config.enabled: false
  outbox-service.enabled: false


logging:
  level:
    root: warn
    com.sap.apm: ${LOGGING_LEVEL_APM:debug}
    com.sap.cds.odata.v4: ${LOGGING_LEVEL_CDS:debug}
    com.sap.cds.handlers: ${LOGGING_LEVEL_CDS:debug}
    com.sap.cds.multitenancy: ${LOGGING_LEVEL_CDS:debug}
    com.sap.cds.persistence.sql: ${LOGGING_LEVEL_CDS:debug}
    com.sap.xsa: ${LOGGING_LEVEL_XSA:warn}